baseURL = "https://maku.blog/"
relativeurls = true
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true
languageCode = "ja-jp"
title = "まくろぐ"
themesDir = "../hugo_themes"
theme = "maku"
googleAnalytics = "UA-63069513-4"

[markup.goldmark.renderer]
  unsafe = true

[params]
  sidebarLogo = "assets/img/site-logo.png"
  image = "assets/img/site-logo-large.png"
  facebookAppId = "1572235596285254"
  description = "まくの日記や雑多メモ。"
  Author = "まく"
  AmazonId = "maku04-22"
  CustomSearchId = "partner-pub-6317852277883092:6890083468"
